#!/usr/bin/env bash
cd $(dirname $0)


# Fetch clang source code
if [ ! -d llvm-project ]; then
    git clone --recursive git@github.com:llvm/llvm-project.git
fi
git -C llvm-project fetch
git -C llvm-project checkout llvmorg-15.0.5

rm -r build.tmp container/dist

docker run -it --rm -u $(id -u):$(id -g) \
    -e CC=clang -e CXX=clang++ \
    -w /var/source \
    -v $(pwd):/var/source \
    registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest \
        cmake -B build.tmp -G Ninja -S llvm-project/llvm \
            -DLLVM_ENABLE_PROJECTS="clang;lld" \
            -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind;compiler-rt" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=container/dist

docker run -it --rm -u $(id -u):$(id -g) \
    -e CC=clang -e CXX=clang++ \
    -w /var/source \
    -v $(pwd):/var/source \
    registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest \
        ninja -C build.tmp all install/strip

# Build the container
cd container
docker build --tag linux-builder .
